import { create } from 'zustand';

export type LanguageCode = 'EN' | 'FR' | 'AR';

interface LangState {
  currentLangCode: LanguageCode;
  setLangCode: (code: LanguageCode) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  EN: {
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.analysis': 'Analysis',
    'nav.about': 'About',
    'nav.company': 'Company',
    'nav.aboutUs': 'About Us',
    'nav.aboutUsDesc': 'Learn more about our company',
    'nav.shop': 'Shop',
    'nav.shopDesc': 'Shop exclusive merchandise',
    'nav.connect': 'Connect',
    'nav.contactUs': 'Contact Us',
    'nav.contactUsDesc': '24/7 Support',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.admin': 'Admin',
    'nav.myCourses': 'My Courses',
    'auth.login.title': 'Login to your account',
    'auth.login.email': 'Email address',
    'auth.login.password': 'Password',
    'auth.login.submit': 'Login',
    'auth.login.rememberMe': 'Remember me',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.signup': 'Sign up',
    'auth.register.title': 'Create your account',
    'auth.register.name': 'Full Name',
    'auth.register.email': 'Email address',
    'auth.register.password': 'Password',
    'auth.register.submit': 'Sign up',
    'auth.register.hasAccount': 'Already have an account?',
    'auth.register.signin': 'Login',
    'auth.placeholder.email': 'name@example.com',
    'auth.placeholder.password': 'Enter your password',
    'auth.placeholder.name': 'Jane Doe',
    'home.hero.title1': 'Master the Markets.',
    'home.hero.title2': 'Fund Your Future.',
    'home.hero.subtitle': 'Professional-grade Forex trading education. Learn price action, risk management, and market psychology from real institutional traders.',
    'home.hero.explore': 'Start Learning',
    'home.hero.analysis': 'Create Free Account',
    'home.hero.badge': 'Live Trading - Forex Market',
    'home.stats.students': 'Active Students',
    'home.stats.content': 'Hours of Content',
    'home.stats.rating': 'Average Rating',
    'home.learn.title': "What You'll Learn",
    'home.learn.f1.title': 'Price Action',
    'home.learn.f1.desc': 'Read the market without indicators',
    'home.learn.f2.title': 'Risk Management',
    'home.learn.f2.desc': 'Protect your capital at all times',
    'home.learn.f3.title': 'Mindset',
    'home.learn.f3.desc': 'The psychological edge of elite traders',
    'home.learn.f4.title': 'Funded Accounts',
    'home.learn.f4.desc': 'Pass prop firm evaluations',
    'home.courses.title': 'Featured Courses',
    'home.courses.subtitle': 'Battle-tested strategies that produce consistent results',
    'home.courses.free': 'FREE',
    'home.courses.free_price': 'Free',
    'home.courses.by': 'by',
    'home.courses.viewAll': 'View All Courses',
    'analysis.title': 'Market Analysis',
    'analysis.subtitle': 'Latest fundamental and technical analysis from trusted financial sources.',
    'analysis.empty': 'No recent analysis found. Check back soon.',
    'analysis.error': 'Failed to load market analysis. Please try again later.',
    'analysis.readMore': 'Read more',
    'footer.risk': 'Trading involves significant risk. Past results do not guarantee future performance.',
    'footer.rights': 'Beyond The Herd. All rights reserved.',
  },
  FR: {
    'nav.home': 'Accueil',
    'nav.courses': 'Cours',
    'nav.analysis': 'Analyse',
    'nav.about': 'À propos',
    'nav.company': 'Entreprise',
    'nav.aboutUs': 'À propos de nous',
    'nav.aboutUsDesc': 'En savoir plus sur notre entreprise',
    'nav.shop': 'Boutique',
    'nav.shopDesc': 'Achetez des produits exclusifs',
    'nav.connect': 'Connecter',
    'nav.contactUs': 'Contactez-nous',
    'nav.contactUsDesc': 'Assistance 24/7',
    'nav.login': 'Connexion',
    'nav.signup': 'S\'inscrire',
    'nav.logout': 'Se déconnecter',
    'nav.admin': 'Admin',
    'nav.myCourses': 'Mes Cours',
    'auth.login.title': 'Connectez-vous à votre compte',
    'auth.login.email': 'Adresse e-mail',
    'auth.login.password': 'Mot de passe',
    'auth.login.submit': 'Se connecter',
    'auth.login.rememberMe': 'Se souvenir de moi',
    'auth.login.noAccount': "Vous n'avez pas de compte ?",
    'auth.login.signup': 'S\'inscrire',
    'auth.register.title': 'Créez votre compte',
    'auth.register.name': 'Nom complet',
    'auth.register.email': 'Adresse e-mail',
    'auth.register.password': 'Mot de passe',
    'auth.register.submit': 'Créer un compte',
    'auth.register.hasAccount': 'Vous avez déjà un compte ?',
    'auth.register.signin': 'Se connecter',
    'auth.placeholder.email': 'nom@example.com',
    'auth.placeholder.password': 'Entrez votre mot de passe',
    'auth.placeholder.name': 'Jane Doe',
    'home.hero.title1': 'Maîtrisez les marchés.',
    'home.hero.title2': 'Financez votre avenir.',
    'home.hero.subtitle': 'Enseignement du trading Forex de niveau professionnel. Apprenez l\'action des prix, la gestion des risques et la psychologie du marché avec de vrais traders institutionnels.',
    'home.hero.explore': 'Commencez à apprendre',
    'home.hero.analysis': 'Créer un compte gratuit',
    'home.hero.badge': 'Trading en direct - Marché du Forex',
    'home.stats.students': 'Étudiants actifs',
    'home.stats.content': 'Heures de contenu',
    'home.stats.rating': 'Note moyenne',
    'home.learn.title': "Ce que vous apprendrez",
    'home.learn.f1.title': 'Action des prix',
    'home.learn.f1.desc': 'Lisez le marché sans indicateurs',
    'home.learn.f2.title': 'Gestion des risques',
    'home.learn.f2.desc': 'Protégez votre capital à tout moment',
    'home.learn.f3.title': 'État d\'esprit',
    'home.learn.f3.desc': 'L\'avantage psychologique des traders d\'élite',
    'home.learn.f4.title': 'Comptes financés',
    'home.learn.f4.desc': 'Réussissez les évaluations des prop firms',
    'home.courses.title': 'Cours en vedette',
    'home.courses.subtitle': 'Des stratégies éprouvées qui produisent des résultats cohérents',
    'home.courses.free': 'GRATUIT',
    'home.courses.free_price': 'Gratuit',
    'home.courses.by': 'par',
    'home.courses.viewAll': 'Voir tous les cours',
    'analysis.title': 'Analyse du marché',
    'analysis.subtitle': 'Dernières analyses fondamentales et techniques provenant de sources financières fiables.',
    'analysis.empty': 'Aucune analyse récente trouvée. Revenez bientôt.',
    'analysis.error': 'Échec du chargement de l\'analyse de marché. Veuillez réessayer plus tard.',
    'analysis.readMore': 'Lire la suite',
    'footer.risk': 'Le trading implique des risques importants. Les résultats passés ne garantissent pas les performances futures.',
    'footer.rights': 'Beyond The Herd. Tous droits réservés.',
  },
  AR: {
    'nav.home': 'الرئيسية',
    'nav.courses': 'الدورات',
    'nav.analysis': 'التحليل',
    'nav.about': 'عنا',
    'nav.company': 'الشركة',
    'nav.aboutUs': 'من نحن',
    'nav.aboutUsDesc': 'تعرف على المزيد حول شركتنا',
    'nav.shop': 'المتجر',
    'nav.shopDesc': 'تسوق البضائع الحصرية',
    'nav.connect': 'تواصل',
    'nav.contactUs': 'اتصل بنا',
    'nav.contactUsDesc': 'دعم على مدار 24/7',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'تسجيل',
    'nav.logout': 'تسجيل خروج',
    'nav.admin': 'المسؤول',
    'nav.myCourses': 'دوراتي',
    'auth.login.title': 'تسجيل الدخول إلى حسابك',
    'auth.login.email': 'البريد الإلكتروني',
    'auth.login.password': 'كلمة المرور',
    'auth.login.submit': 'تسجيل الدخول',
    'auth.login.rememberMe': 'تذكرني',
    'auth.login.noAccount': 'ليس لديك حساب؟',
    'auth.login.signup': 'إنشاء حساب',
    'auth.register.title': 'إنشاء حسابك',
    'auth.register.name': 'الاسم الكامل',
    'auth.register.email': 'البريد الإلكتروني',
    'auth.register.password': 'كلمة المرور',
    'auth.register.submit': 'إنشاء حساب',
    'auth.register.hasAccount': 'هل لديك حساب بالفعل؟',
    'auth.register.signin': 'تسجيل الدخول',
    'auth.placeholder.email': 'name@example.com',
    'auth.placeholder.password': 'أدخل كلمة المرور الخاصة بك',
    'auth.placeholder.name': 'Jane Doe',
    'home.hero.title1': 'أتقن الأسواق.',
    'home.hero.title2': 'مول مستقبلك.',
    'home.hero.subtitle': 'تعليم احترافي لتداول الفوركس. تعلم حركة السعر، وإدارة المخاطر، وسيكولوجية السوق من متداولين مؤسسيين حقيقيين.',
    'home.hero.explore': 'ابدأ التعلم',
    'home.hero.analysis': 'إنشاء حساب مجاني',
    'home.hero.badge': 'التداول المباشر - سوق الفوركس',
    'home.stats.students': 'طلاب نشطون',
    'home.stats.content': 'ساعات من المحتوى',
    'home.stats.rating': 'متوسط التقييم',
    'home.learn.title': 'ماذا ستتعلم',
    'home.learn.f1.title': 'حركة السعر',
    'home.learn.f1.desc': 'قراءة السوق بدون مؤشرات',
    'home.learn.f2.title': 'إدارة المخاطر',
    'home.learn.f2.desc': 'حماية رأس مالك في جميع الأوقات',
    'home.learn.f3.title': 'العقلية',
    'home.learn.f3.desc': 'الميزة النفسية للمتداولين النخبة',
    'home.learn.f4.title': 'الحسابات الممولة',
    'home.learn.f4.desc': 'اجتياز تقييمات شركات التمويل',
    'home.courses.title': 'الدورات المميزة',
    'home.courses.subtitle': 'استراتيجيات مجربة في السوق تنتج نتائج متسقة',
    'home.courses.free': 'مجاني',
    'home.courses.free_price': 'مجاني',
    'home.courses.by': 'بواسطة',
    'home.courses.viewAll': 'عرض جميع الدورات',
    'analysis.title': 'تحليل السوق',
    'analysis.subtitle': 'أحدث التحليلات الأساسية والفنية من مصادر مالية موثوقة.',
    'analysis.empty': 'لم يتم العثور على تحليل حديث. تحقق مرة أخرى قريبا.',
    'analysis.error': 'فشل تحميل تحليل السوق. يرجى المحاولة مرة أخرى لاحقًا.',
    'analysis.readMore': 'اقرأ المزيد',
    'footer.risk': 'ينطوي التداول على مخاطر كبيرة. النتائج السابقة لا تضمن الأداء المستقبلي.',
    'footer.rights': 'Beyond The Herd. جميع الحقوق محفوظة.',
  },
};

export const useLangStore = create<LangState>((set, get) => ({
  currentLangCode: 'EN',
  setLangCode: (code) => {
    set({ currentLangCode: code });
    document.documentElement.dir = code === 'AR' ? 'rtl' : 'ltr';
    document.documentElement.lang = code.toLowerCase();
  },
  t: (key) => {
    const { currentLangCode } = get();
    return translations[currentLangCode]?.[key] || key;
  }
}));
